### ISSUE TITLE
The Plugin isn't enabling and kills the server.

### ISSUE THREAD

**Issue by darkwolfie37** [IkeVoodoo/LSSMP#133]
https://youtu.be/GG5QEkZ2SXg heres a video i made about the issue

**Comment by darkwolfie37** [comment]
The Server did start responding after about a minute for some odd reason
So Idk what the fuck happened.

**Comment by IkeVoodoo** [comment]
Weird, this should have been fixed in around version 1.6, however pebblehost does probably stop pinging servers, which is what my plugin does to notify you for updates, I'll add an on/off switch for it next version (The thing holding back the new version is literally a problem with the translation manager)

**Comment by darkwolfie37** [comment]
> Weird, this should have been fixed in around version 1.6, however pebblehost does probably stop pinging servers, which is what my plugin does to notify you for updates, I'll add an on/off switch for it next version (The thing holding back the new version is literally a problem with the translation manager)

Thanks Mate. But i would recommend the plugin as you've done a great job! Runs very smooth!
