### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by ChrisChrome** [IkeVoodoo/LSSMP#208]
The license you have on the github project, and the notes you have in README.md, don't seem to agree.
With GPL-3, commercial use is allowed, but you say it's not in your notes

TL;DR you should update your license and/or README.md to match

![image](https://user-images.githubusercontent.com/28414320/181653482-acf3405b-4d8b-4ccb-a8a2-6d7d37be3585.png)

**Comment by Makonede** [comment]
> The license you have on the github project, and the notes you have in README.md, don't seem to agree.
> With GPL-3, commercial use is allowed, but you say it's not in your notes
> 
> TL;DR you should update your license and/or README.md to match
> 
> ![image](https://user-images.githubusercontent.com/28414320/181653482-acf3405b-4d8b-4ccb-a8a2-6d7d37be3585.png)
> 

+1. also, all use and modification, whether public, private, commercial, or otherwise, is allowed, as well as redistribution of any modified or unmodified copies, anywhere, of software licensed under any open source license, of which the GNU GPLv3 is one. with the project licensed under the GPLv3, your `NOTES` section is completely irrelevant. consider removing this section from the README.

**Comment by Makonede** [comment]
@ChrisChrome fixed; you may close this issue
